services:
  surah-splitter:
    build:
      context: .
      dockerfile: Dockerfile
    image: surah-splitter:latest
    container_name: surah-splitter-api
    init: true
    ports:
      - "${API_PORT:-8001}:8001"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - LOG_LEVEL=INFO
      - RELOAD=true
    volumes:
      # Mount source code for hot-reload
      - ./src:/app/src
      - ./templates:/app/templates
      - ./static:/app/static
      - ./data:/app/data
      # Persistent volumes for runtime data
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./uploads:/app/uploads
    restart: unless-stopped
    command: ["uvicorn", "src.surah_splitter.api.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"